apiVersion: v1
kind: Pod
metadata:
  name: busyboxplus-curl
  namespace: todoapp
  labels:
    app: todoapp
spec:
  containers:
  - name: busyboxplus-curl
    image: ikulyk404/busyboxplus:curl
    ports:
    - containerPort: 8000