apiVersion: v1
kind: Pod
metadata:
  name: todoapp-pod
  namespace: todoapp
  labels:
    app: todoapp
spec:
  containers:
  - name: todoapp-container
    image: whatislavx/todoapp:3.0.0
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: health/liveness/
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 5
    readinessProbe:
      httpGet:
        path: health/readiness/
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 5
